services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_PASSWORD: superSecretPasswordPleaseChangeMe
      POSTGRES_USER: postgres
      POSTGRES_DB: monetr
    volumes:
      - postgresData:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    restart: unless-stopped
  redis:
    image: redis:6.2.16-alpine
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    restart: unless-stopped
  monetr:
    image: ghcr.io/monetr/monetr:latest
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:4000/api/health" ]
      interval: 5s
      timeout: 5s
      retries: 24
      start_period: 30s
    restart: unless-stopped
    command:
      - serve
      # Setup the database and perform migrations.
      - --migrate
      # Since certificates will not have been created, make some.
      - --generate-certificates
    ports:
      - "4000:4000"
    links:
      - redis
      - postgres
    depends_on:
      redis:
        condition: service_started
      postgres:
        condition: service_started
    volumes:
      # Contains certificates generated on startup as well as config
      - monetrData:/etc/monetr
    environment:
      # After creating your own user, it is recommended to disable sign ups if
      # your monetr instance is exposed to the public internet. Otherwise
      # strangers may be able to use your instance themselves.
      MONETR_ALLOW_SIGN_UP: ${MONETR_ALLOW_SIGN_UP:-true}
      MONETR_PG_USERNAME: postgres
      MONETR_PG_PASSWORD: superSecretPasswordPleaseChangeMe
      MONETR_PG_DATABASE: monetr
      MONETR_PG_ADDRESS: postgres
      MONETR_REDIS_ENABLED: "true"
      MONETR_REDIS_ADDRESS: redis
      MONETR_PLAID_CLIENT_ID: ${MONETR_PLAID_CLIENT_ID}
      MONETR_PLAID_CLIENT_SECRET: ${MONETR_PLAID_CLIENT_SECRET}
      MONETR_PLAID_ENVIRONMENT: ${MONETR_PLAID_ENVIRONMENT}
      MONETR_SENTRY_DSN: ${MONETR_SENTRY_DSN}
      MONETR_SENTRY_EXTERNAL_DSN: ${MONETR_SENTRY_EXTERNAL_DSN:-${MONETR_SENTRY_DSN}}
      MONETR_SERVER_EXTERNAL_URL: ${MONETR_SERVER_EXTERNAL_URL:-http://localhost:4000}
      MONETR_STORAGE_ENABLED: ${MONETR_STORAGE_ENABLED:-true}
      MONETR_STORAGE_PROVIDER: ${MONETR_STORAGE_PROVIDER:-filesystem}

volumes:
  monetrData:
  postgresData:
