replicaCount: 6

image:
  repository: ghcr.io/monetr/monetr
  pullPolicy: Always
  tag: "" # Will be overwritten with the SHA for the commit of this deploy

imagePullSecrets: [ ]

podAnnotations:
  prometheus.io/scrape: 'true'
  prometheus.io/port: '9000'

serviceAccountName: monetr

service:
  enabled: true
  port: 4000

ingress:
  # Managed elsewhere
  enabled: false

resources:
  limits:
    cpu: 200m
    memory: 512Mi
  requests:
    cpu: 50m
    memory: 256Mi

nodeSelector:
  kubernetes.io/os: linux
  kubernetes.io/arch: amd64

disruption:
  enabled: false
  maxUnavailable: 1
  minAvailable: 1

customEnvFrom:
  - secretRef:
      name: monetr-config-secrets

extraEnv:
  - name: MONETR_ENVIRONMENT
    value: "my.monetr.app"
  - name: AWS_ACCESS_KEY_ID
    valueFrom:
      secretKeyRef:
        key: AccessKey
        name: rook-ceph-object-user-rados-monetr
        optional: false
  - name: AWS_SECRET_ACCESS_KEY
    valueFrom:
      secretKeyRef:
        key: SecretKey
        name: rook-ceph-object-user-rados-monetr
        optional: false

extraVolumes:
  - name: authentication-certificates
    secret:
      secretName: monetr-authentication-certificate
  - name: vault-config
    configMap:
      name: monetr-vault-config
  - name: vault-tls
    csi:
      driver: csi.cert-manager.io
      readOnly: true
      volumeAttributes:
        csi.cert-manager.io/issuer-name: monetr-ca-issuer
        csi.cert-manager.io/issuer-kind: ClusterIssuer
        csi.cert-manager.io/common-name: vault.security.svc.cluster.local
        csi.cert-manager.io/dns-names: vault.security.svc.cluster.local
        csi.cert-manager.io/duration: 2160h # 90d
        csi.cert-manager.io/usages: digital signature,key encipherment
  - name: monetr-tls
    secret:
      secretName: my-monetr-app-tls
  - name: google-service-account
    secret:
      secretName: monetr-google-service-account

extraVolumeMounts:
  - name: authentication-certificates
    mountPath: /etc/monetr/authentication
    readOnly: true
  - name: tls
    mountPath: /etc/monetr/tls
    readOnly: true
  - name: vault-config
    mountPath: /etc/monetr/vault/config
    readOnly: true
  - name: vault-tls
    mountPath: /etc/monetr/vault/tls
    readOnly: true
  - name: google-service-account
    mountPath: /etc/monetr/google
    readOnly: true

api:
  name: monetr
  allowSignUp: true
  server:
    externalUrl: https://my.monetr.app
    tlsCertificate: /etc/monetr/tls/tls.crt
    tlsKey: /etc/monetr/tls/tls.key
  beta:
    enableBetaCodes: true
  postgreSql:
    address: pgbouncer.database.svc.cluster.local
    port: 5432
    database: monetr
  email:
    enabled: true
    domain: monetr.app
    forgotPassword:
      enabled: true
      tokenLifetime: 10m
    verification:
      enabled: true
      tokenLifetime: 30m
    smtp:
      username: apikey
      host: smtp.sendgrid.net
      port: 587
  reCaptcha:
    enabled: false
    verifyLogin: false
    verifyRegister: false
    verifyForgotPassword: false
  links:
    maxNumberOfLinks: 3
  plaid:
    environment: "https://production.plaid.com"
    enableReturningUserExperience: true
    webhooksEnabled: true
    webhooksDomain: my.monetr.app
    oauthDomain: my.monetr.app
  cors:
    allowedOrigins:
      - "https://my.monetr.app"
    debug: false
  redis:
    enabled: true
    address: redis.redis.svc.cluster.local
    port: 6379
  logging:
    level: debug
    format: json
    stackDriver:
      enabled: false
  sentry:
    enabled: true
    sampleRate: 1.0
    traceSampleRate: 1.0
  keyManagement:
    enabled: true
    provider: vault
    google:
      resourceName: projects/production-362403/locations/us/keyRings/monetr-production-362403-monetr-in/cryptoKeys/monetr-secrets-monetr-production-362403-monetr-in
      credentialsJSON: /etc/monetr/google/service-account.json
  security:
    privateKey: /etc/monetr/authentication/tls.key
  storage:
    enabled: true
    provider: s3
    s3:
      endpoint: http://rook-ceph-rgw-rados.ceph.svc.cluster.local
      bucket: objects.monetr.min4.monetr.in
      region: rados
      forcePathStyle: true
      useEnvCredentials: true
  stripe:
    enabled: true
    webhooksEnabled: true # Still working on this for now.
    billingEnabled: true
    taxesEnabled: true
    freeTrialDays: 30
    initialPlan:
      stripePriceId: price_1LkF9dI4uGGnwpgwvGIFcfZm
      features:
        - ManualBudgeting
        - LinkedBudgeting

